name: Create Release

# Create XCFramework when a version is tagged
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  create_release:
    name: Create Release
    runs-on: macos-12
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: swift build -v -c release
      - name: Test
        run: swift test -v
      - uses: actions/upload-artifact@main
        with:
            name: KSPlayer
            path: Sources
